version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: gera
      POSTGRES_DB: crm_db
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
    postgres:
